modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "armadillo_boxes"
version = "0.1.0"
displayName = "Armadillo Boxes"
authors = "MrSterner"
description = '''
Shulker boxes but armadillo
'''
#logoFile = ""

[[dependencies.armadillo_boxes]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armadillo_boxes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armadillo_boxes]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "armadillo_boxes.mixins.json"